### ISSUE TITLE
Calibration of the Kinect with the Projector

### ISSUE THREAD

**Issue by iamlegolas** [SaranshKejriwal/projectorUI#1]
I don't understand at all how you've managed to calibrate the two. Please elaborate a bit. 

Thanks!

**Comment by SaranshKejriwal** [comment]
What you need to account for is the distance between the wall and the Kinect. The projector need not be specially calibrated, as long as its principle axis is parallel to that of the Kinect.

If the distance between the wall and the Kinect is 'd' units, then the distance between your hand and Kinect when you draw on the UI is slightly lesser( say d1), and that of your head and body will be even lesser(say d2). So d>d1>d2.

If the Kinect's disparity map value at d is 'I', at d1 is I1 and at d2 is I2, where 0< I,I1,I2<255 and I2<I1<I, you need to apply a threshold on the disparity map for values around I1, so that only the disparity just near your hand is tracked, and that of the wall and your body is excluded.

**Comment by iamlegolas** [comment]
The principle axes of the Kinect and the projector are not parallel. Do you have any idea how I can calibrate the two using Python and OpenCV? I need to detect an item in the real world and project onto it. 

Thanks!

**Comment by SaranshKejriwal** [comment]
If you're capturing the same object that you're projecting on, then my understanding is that the epipolar lines of the projector and Kinect should converge at that object.

In my code, I didn't require to calibrate the projector using OpenCV at all. My Kinect received input from the disparity of my hand, which I drew on a green colored Mat object (called ui in my code). Then I simply performed imshow on ui and projected my screen on myself. Had the principle axes not been aligned, the algo would've worked, but it would've drawn elsewhere
